/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import heap.Heap;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import avl.AVL;

public class Huffman {

    public static void main(String[] args) {
      String text = "could not find file";

      try {
        File f = new File(args[0]);

        Scanner sc = new Scanner(f);

        text = sc.hasNext() ? sc.next() : "Could Not find file";

        System.out.println(text);

      } catch(FileNotFoundException e) {

        System.err.println("file not found exception");
      }

        HuffmanTree test = new HuffmanTree(); 
        String bitstring = test.encode(text);

        System.out.println(test.decode(test.encode(text)).equals(text));

        // System.out.println(text.length());
        // System.out.println(bitstring.length());
        System.out.println(bitstring.length() / text.length() / 8.0);

        if (text.length() < 100) {

          System.out.println(text);

          System.out.println(bitstring);

          System.out.println(test.decode(bitstring));
        }

        // test.test();
        // test.encode("fig");
        // System.out.println(test.encode("gif"));
    }
}
