/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;

import heap.Heap;
import avl.AVL;

public class Huffman {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new Huffman().getGreeting());
        HuffmanTree test = new HuffmanTree();
        // test.test();
        System.out.println(test.encode("gif"));
        System.out.println(test.decode(test.encode("iffggi")));
    }
}
